---
- name: create pycharm directory
  file:
    path: /home/{{ install_user }}/bin
    state: directory
    mode: 0775
    owner: "{{ install_user }}"
    group: "{{ install_user }}"

- name: download pycharm
  get_url:
    url: "http://download.jetbrains.com/python/pycharm-professional-{{ pycharm }}.tar.gz"
    dest: /tmp/pycharm-{{ pycharm }}.tar.gz

- name: unarchive pycharm
  unarchive: 
    src: /tmp/pycharm-{{ pycharm}}.tar.gz 
    dest: /home/{{ install_user }}/bin
    mode: 0775
    owner: "{{ install_user }}"
    group: "{{ install_user }}"

- name: set permissions on pycharm
  file:
    path: /home/{{ install_user }}/bin/pycharm-{{ pycharm }}
    state: directory
    recurse: yes
    mode: 0775
    owner: "{{ install_user }}"
    group: "{{ install_user }}"


